config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity-profiler:
      branch: fix/sqa
      repo: https://github.com/IraitzM/data-complexity-profiler
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-purple-anteater.sh
        container: qc.acc_clammy-dandelion-echidna
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity-profiler find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-copper-llama.sh
        container: qc.doc_squirrely-xanthic-albatross
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-rust-booby.sh
        container: qc.doc_snappy-linen-stoat
      github.com/IraitzM/data-complexity-profiler markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-zucchini-dragon.sh
        container: qc.doc_frumpy-saffron-otter
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity-profiler licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-saffron-mist.sh
        container: qc.lic_chummy-zucchini-lemur
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity-profiler cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-peach-hyena.sh
        container: qc.met_boozy-buff-sloth
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity-profiler bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-pumpkin-caracal.sh
        container: qc.sec_lanky-sapphire-weasel
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity-profiler flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-beige-collie.sh
        container: qc.sty_seedy-cinnamon-cat
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity-profiler tox:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-auburn-sponge.sh
        container: qc.uni_craggy-ivory-eleuth
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity-profiler get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-smalt-yak.sh
        container: qc.ver_gamy-plum-ladybird
timeout: 5400
