config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity-profiler:
      branch: main
      repo: https://github.com/IraitzM/data-complexity-profiler
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-gamboge-dachsbracke.sh
        container: qc.acc_cozy-wisteria-bandicoot
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity-profiler find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-bistre-dachshund.sh
        container: qc.doc_snoopy-cobalt-greyhound
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-malachite-cockroach.sh
        container: qc.doc_flimsy-charcoal-chamois
      github.com/IraitzM/data-complexity-profiler markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-indigo-walrus.sh
        container: qc.doc_craggy-black-ferret
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity-profiler licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ecru-dormouse.sh
        container: qc.lic_flabby-cream-impala
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity-profiler cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-magnolia-gar.sh
        container: qc.met_stuffy-black-monster
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity-profiler bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-olivine-shrew.sh
        container: qc.sec_homely-cobalt-antelope
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity-profiler flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-crimson-coral.sh
        container: qc.sty_wheezy-copper-bordeaux
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity-profiler pytest:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-mustard-havanese.sh
        container: qc.uni_chewy-cerulean-loon
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity-profiler get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-denim-turtle.sh
        container: qc.ver_muzzy-platinum-mongoose
timeout: 5400
