config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity-profiler:
      branch: fix/sqa
      repo: https://github.com/IraitzM/data-complexity-profiler
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-alizarin-hamster.sh
        container: qc.acc_sleazy-amber-fox
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity-profiler find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-viridian-catfish.sh
        container: qc.doc_randy-ultramarine-labradoodle
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-olive-horse.sh
        container: qc.doc_lovely-chocolate-bloodhound
      github.com/IraitzM/data-complexity-profiler markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-olive-foxhound.sh
        container: qc.doc_foggy-copper-flamingo
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity-profiler licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-pear-chimpanzee.sh
        container: qc.lic_flimsy-vermilion-dodo
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity-profiler cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-myrtle-lemming.sh
        container: qc.met_jumpy-cardinal-earwig
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity-profiler bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cerulean-squirrel.sh
        container: qc.sec_wheezy-orchid-gecko
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity-profiler flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-silver-urchin.sh
        container: qc.sty_ready-auburn-wombat
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity-profiler pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-copper-anteater.sh
        container: qc.uni_tacky-razzmatazz-armadillo
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity-profiler get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-smalt-frigatebird.sh
        container: qc.ver_tacky-fuchsia-meerkat
timeout: 5400
