config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity-profiler:
      branch: fix/sqa
      repo: https://github.com/IraitzM/data-complexity-profiler
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-orchid-lionfish.sh
        container: qc.acc_foggy-cinnabar-millipede
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity-profiler find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-myrtle-crocodile.sh
        container: qc.doc_freaky-lilac-dachsbracke
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-wisteria-peccary.sh
        container: qc.doc_freaky-scarlet-caracal
      github.com/IraitzM/data-complexity-profiler markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-dandelion-hummingbird.sh
        container: qc.doc_muggy-amethyst-cheetah
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity-profiler licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-carmine-barracuda.sh
        container: qc.lic_frumpy-amethyst-devil
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity-profiler cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-champagne-quokka.sh
        container: qc.met_pasty-amber-beagle
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity-profiler bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-copper-ladybird.sh
        container: qc.sec_skimpy-plum-markhor
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity-profiler flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-grey-barracuda.sh
        container: qc.sty_zippy-harlequin-liger
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity-profiler tox:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-goldenrod-audemer.sh
        container: qc.uni_lanky-thistle-starfish
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity-profiler get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-mauve-eagle.sh
        container: qc.ver_ugly-dandelion-jaguar
timeout: 5400
