config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity-profiler:
      branch: fix/sqa
      repo: https://github.com/IraitzM/data-complexity-profiler
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-sepia-mole.sh
        container: qc.acc_tasty-amber-russel
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity-profiler find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-brass-wasp.sh
        container: qc.doc_snippy-violet-wildebeest
      github.com/IraitzM/data-complexity-profiler git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-magnolia-bat.sh
        container: qc.doc_cloudy-white-flounder
      github.com/IraitzM/data-complexity-profiler markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-silver-hare.sh
        container: qc.doc_cranky-viridian-dodo
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity-profiler licensee:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-magnolia-bison.sh
        container: qc.lic_geeky-harlequin-mammoth
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity-profiler cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-fuchsia-mole.sh
        container: qc.met_crappy-fuchsia-wasp
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity-profiler bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-amber-snail.sh
        container: qc.sec_homey-ruby-dunker
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity-profiler flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-tangerine-cockroach.sh
        container: qc.sty_pasty-purple-pinscher
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity-profiler tox:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-cream-frise.sh
        container: qc.uni_nerdy-cinnamon-devil
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity-profiler get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-chestnut-starfish.sh
        container: qc.ver_chewy-gold-gecko
timeout: 5400
